server:
  port: 5678
  app_name: DemoServer
  microservice_name: ConnectionManager
  prefix_main: DemoServer_ConnectionManager
  prefix_worker: DemoServer_ConnectionManager_Worker
  http_read_timeout: 300
  http_write_timeout: 300
  http_idle_timeout: 300
  http_shutdown_timeout: 30
  worker_sleep_time: 5
  list_limit: 10
configuration:
  refresh_cycle: 60
  log_folder: ./logs
  log_file: DemoServer_ConnectionManager_log.json
postgres:
  host: 127.0.0.1
  port: 5432
  rousername: foo
  rwusername: foo
  ropassword: bar
  rwpassword: bar
  roconnectionpoolsize: 425
  rwconnectionpoolsize: 425
  sslmode: false
vault:
  host: 127.0.0.1
  port: 8200
  roleid: foo
  secretid: bar
  https: true
  tlsskipverify: false
  pathprefix: demoserver
otlp:
  host: 127.0.0.1
  port: 4318
  endpoint: 
  https: true
  tlsskipverify: false
  batchduration: 5
datalayer:
  name_prefix: DemoServer_ConnectionManager
  max_results: 10000
aws:
  default_lease_ttl: 20
  max_lease_ttl: 0
  iam_user_latency: 10
  default_sts_ttl: 900