basePath: /v1/connectionmgmt
consumes:
    - application/json
definitions:
    Connection:
        description: |-
            Connection represents generic Connection resource returned by Microservice endpoints
            Different types of connections (for example: AWSConnection) contains an object of
            Connection inside.
        x-go-package: main/data
    ConnectionWrapper:
        description: |-
            Connection represents generic Connection attributes which are allowed in POST or
            PATCH schema.
        x-go-package: main/data
    DeleteAWSConnectionResponse:
        description: Response schema for DELETE - DeleteAWSConnection
        x-go-package: main/handlers
    ErrorResponse:
        description: |-
            ErrorResponse represents information returned by Microservice endpoints in case that was an error
            in normal execution flow.
        x-go-package: main/helper
    AWSConnection:
        description: JiraConnection represents JiraConnection resource returned by Microservice endpoints
        x-go-package: main/data
    JiraConnectionWrapper:
        description: |-
            JiraConnectionWrapper represents JiraConnection attributes which are allowed in POST or
            PATCH schema.
        x-go-package: main/data
    StatusResponse:
        description: Response schema for ConnectionManager Status GET
        x-go-package: main/handlers
    TestJiraConnectionResponse:
        description: Response schema for GET - TestJiraConnection
        x-go-package: main/handlers
info:
    contact:
        email: waqar.ahmed@gmail.com
        name: Waqar Ahmed
    description: |-
        Connection defines how and where to authenticate for RuLe. A connection can be defined for terminal actions
        like Jira Issue Creation or EveryDollar Transaction entry, as well as extraction sources like Gmail Account for email based records,..
        It can also be identity provider such as OpenID endpoint or LDAP or AD.
        ConnectionManager serves as one stop shop for CRUD as well as connectivity testing capabilities for all connection types for RuLe.
    termsOfService: there are no TOS at this moment, use at your own risk we take no responsibility
    title: RuLe_ConnectionManager API.
    version: 1.0.0
paths:
    /Test:
        get:
            description: |-
                Endpoint: GET - /v1/connectionmgmt/connection/jira/test/{connectionid}

                Description: Test connectivity of specified JiraConnection resource.
            operationId: TestJiraConnection
            parameters:
                - description: id for JiraConnection resource to be retrieved. expected to be in uuid format i.e. XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
                  in: query
                  name: connectionid
                  required: true
                  type: string
            produces:
                - application/json
            responses:
                "200":
                    description: Connectivity test status
                    schema:
                        $ref: '#/definitions/TestJiraConnectionResponse'
                "404":
                    description: Resource not found. Resources are filtered based on connectiontype = JiraConnectionType. If connectionid of Non-JiraConnection is provided ResourceNotFound error is returned.
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                "500":
                    description: Internal server error
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                default:
                    description: unexpected error
                    schema:
                        $ref: '#/definitions/ErrorResponse'
            summary: GET - TestJiraConnection
            tags:
                - JiraConnection
    /connection:
        get:
            description: |-
                Endpoint: GET - /v1/connectionmgmt/connection/jira/{connectionid}

                Description: Returns JiraConnection resource based on connectionid.
            operationId: GetJiraConnection
            parameters:
                - description: id for JiraConnection resource to be retrieved. expected to be in uuid format i.e. XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
                  in: query
                  name: connectionid
                  required: true
                  type: string
            produces:
                - application/json
            responses:
                "200":
                    description: JiraConnection resource
                    schema:
                        $ref: '#/definitions/JiraConnection'
                "404":
                    description: Resource not found. Resources are filtered based on connectiontype = JiraConnectionType. If connectionid of Non-JiraConnection is provided ResourceNotFound error is returned.
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                "500":
                    description: Internal server error
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                default:
                    description: unexpected error
                    schema:
                        $ref: '#/definitions/ErrorResponse'
            summary: GET - JiraConnection
            tags:
                - JiraConnection
    /connections:
        get:
            description: |-
                Endpoint: GET - /v1/connectionmgmt/connections

                Description: Returns list of generic connections resources. It is useful to list all connections
                currently in ConnectionManager. Generic Connection resourse does not have specific details
                and attributes of specialized connection types. It only tracks general information about
                connection including its type.
            operationId: GetConnections
            parameters:
                - description: maximum number of results to return.
                  format: int32
                  in: query
                  name: limit
                  type: integer
                - description: number of results to be skipped from beginning of list
                  format: int32
                  in: query
                  name: skip
                  type: integer
            produces:
                - application/json
            responses:
                "200":
                    description: List of JiraConnection resources
                    schema:
                        items:
                            $ref: '#/definitions/JiraConnection'
                        type: array
                "400":
                    description: Issues with parameters or their value
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                "500":
                    description: Internal server error
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                default:
                    description: unexpected error
                    schema:
                        $ref: '#/definitions/ErrorResponse'
            summary: GET - Connections
            tags:
                - Connection
    /connections/jira:
        get:
            description: |-
                Endpoint: GET - /v1/connectionmgmt/connections/jira

                Description: Returns list of JiraConnection resources. Each JiraConnection resource
                contains generic underlying generic Connection resource as well as JiraConnection
                specific attributes.
            operationId: GetJiraConnections
            parameters:
                - description: maximum number of results to return.
                  format: int32
                  in: query
                  name: limit
                  type: integer
                - description: number of results to be skipped from beginning of list
                  format: int32
                  in: query
                  name: skip
                  type: integer
            produces:
                - application/json
            responses:
                "200":
                    description: List of JiraConnection resources
                    schema:
                        items:
                            $ref: '#/definitions/JiraConnection'
                        type: array
                "400":
                    description: Issues with parameters or their value
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                "500":
                    description: Internal server error
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                default:
                    description: unexpected error
                    schema:
                        $ref: '#/definitions/ErrorResponse'
            summary: GET - JiraConnections
            tags:
                - JiraConnection
    /jira:
        delete:
            description: |-
                Endpoint: DELETE - /v1/connectionmgmt/connection/jira/{connectionid}

                Description: Returns JiraConnection resource based on connectionid.
            operationId: DeleteJiraConnection
            parameters:
                - description: id for JiraConnection resource to be retrieved. expected to be in uuid format i.e. XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
                  in: query
                  name: connectionid
                  required: true
                  type: string
            produces:
                - application/json
            responses:
                "200":
                    description: Resource successfully deleted.
                    schema:
                        $ref: '#/definitions/DeleteJiraConnectionResponse'
                "404":
                    description: Resource not found.
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                "500":
                    description: Internal server error
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                default:
                    description: unexpected error
                    schema:
                        $ref: '#/definitions/ErrorResponse'
            summary: DELETE - JiraConnection
            tags:
                - JiraConnection
        patch:
            consumes:
                - application/json
            description: |-
                Endpoint: PATCH - /v1/connectionmgmt/connection/jira/{connectionid}

                Description: Update attributes of JiraConnection resource. Update operation resets Tested status of JiraConnection and connection is not used by active rules anymore.
            operationId: UpdateJiraConnection
            parameters:
                - description: id for JiraConnection resource to be retrieved. expected to be in uuid format i.e. XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
                  in: query
                  name: connectionid
                  required: true
                  type: string
                - description: JSON string defining JiraConnection resource. Change of connectiontype and ID attributes is not allowed.
                  in: body
                  name: Body
                  required: true
                  schema:
                    $ref: '#/definitions/JiraConnectionWrapper'
            produces:
                - application/json
            responses:
                "200":
                    description: JiraConnection resource after updates.
                    schema:
                        $ref: '#/definitions/JiraConnection'
                "500":
                    description: Internal server error
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                default:
                    description: unexpected error
                    schema:
                        $ref: '#/definitions/ErrorResponse'
            summary: PATCH - JiraConnection
            tags:
                - JiraConnection
        post:
            consumes:
                - application/json
            description: |-
                Endpoint: GET - /v1/connectionmgmt/connection/jira

                Description: Create new JiraConnection resource.
            operationId: AddJiraConnection
            parameters:
                - description: JSON string defining JiraConnection resource
                  in: body
                  name: Body
                  required: true
                  schema:
                    $ref: '#/definitions/JiraConnectionWrapper'
            produces:
                - application/json
            responses:
                "200":
                    description: JiraConnection resource just created.
                    schema:
                        $ref: '#/definitions/JiraConnection'
                "500":
                    description: Internal server error
                    schema:
                        $ref: '#/definitions/ErrorResponse'
                default:
                    description: unexpected error
                    schema:
                        $ref: '#/definitions/ErrorResponse'
            summary: POST - AddJiraConnection
            tags:
                - JiraConnection
    /status:
        get:
            description: |-
                Endpoint: GET - /v1/connectionmgmt/status


                Description: Returns status of ConnectionManager Instance
            operationId: GetStatus
            produces:
                - application/json
            responses:
                "200":
                    description: StatusReponse
                    schema:
                        $ref: '#/definitions/StatusResponse'
                default:
                    description: unexpected error
                    schema:
                        $ref: '#/definitions/ErrorResponse'
            summary: GET - Status
            tags:
                - Status
produces:
    - application/json
schemes:
    - http
swagger: "2.0"
