issues:
  exclude-use-default: false
  exclude-dirs:
    - postgres/pgdata
    - e2e_test
linters:
  enable:
    - typecheck
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocyclo
    - goconst
    - goimports
    - misspell
    - unconvert
    - unparam
    - bodyclose
    - nakedret
    - tparallel